Profiles:
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        AdminPrincipal: ""
        AnchorPeers:
        - Host: peer0.org1.example.com
          Port: 7051
      - Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
        AdminPrincipal: ""
        AnchorPeers:
        - Host: peer0.org2.example.com
          Port: 7051
    Orderer: null
    Consortiums: {}
  TwoOrgsOrdererGenesis:
    Consortium: ""
    Application: null
    Orderer:
      OrdererType: solo
      Addresses:
      - orderer.example.com:7050
      BatchTimeout: 0s
      BatchSize:
        MaxMessageCount: 0
        AbsoluteMaxBytes: 0
        PreferredMaxBytes: 0
      Kafka:
        Brokers: []
      Organizations:
      - Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        AdminPrincipal: ""
        AnchorPeers: []
      MaxChannels: 0
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
          AdminPrincipal: ""
          AnchorPeers:
          - Host: peer0.org1.example.com
            Port: 7051
        - Name: Org2MSP
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
          AdminPrincipal: ""
          AnchorPeers:
          - Host: peer0.org2.example.com
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/example.com/msp
  AdminPrincipal: ""
  AnchorPeers: []
- Name: Org1MSP
  ID: Org1MSP
  MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
  AdminPrincipal: ""
  AnchorPeers:
  - Host: peer0.org1.example.com
    Port: 7051
- Name: Org2MSP
  ID: Org2MSP
  MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
  AdminPrincipal: ""
  AnchorPeers:
  - Host: peer0.org2.example.com
    Port: 7051
Application: null
Orderer:
  OrdererType: solo
  Addresses:
  - orderer.example.com:7050
  BatchTimeout: 0s
  BatchSize:
    MaxMessageCount: 0
    AbsoluteMaxBytes: 0
    PreferredMaxBytes: 0
  Kafka:
    Brokers: []
  Organizations:
  - Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    AdminPrincipal: ""
    AnchorPeers: []
  MaxChannels: 0
