OrdererOrgs:
- Name: Orderer
  Domain: example.com
  CA:
    Hostname: ""
    CommonName: ""
    SANS: []
  Template:
    Count: 0
    Start: 0
    Hostname: ""
    SANS: []
  Specs:
  - Hostname: orderer
    CommonName: ""
    SANS: []
  Users:
    Count: 0
PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  CA:
    Hostname: ""
    CommonName: ""
    SANS: []
  Template:
    Count: 2
    Start: 0
    Hostname: ""
    SANS: []
  Specs: []
  Users:
    Count: 1
- Name: Org2
  Domain: org2.example.com
  CA:
    Hostname: ""
    CommonName: ""
    SANS: []
  Template:
    Count: 2
    Start: 0
    Hostname: ""
    SANS: []
  Specs: []
  Users:
    Count: 1
